### ISSUE TITLE
[Script 4: Text to Speech] Is reading limiting?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#12]
Sequence 1 has onscreen 'Having to read everything can be limiting – especially in terms of audience' and the text in sequence 2 starts with 'Having to read everything can be limiting'.

I am not sure about the word 'limiting'. I am not sure it is explained enough as to why it is limiting or why this limit is a problem.

I wonder if it woudn't be better to talk about it in terms of 'For some people reading can be challenging'...?

**Comment by yatil** [comment]
I also think limiting is a very negative word to use. Why not using something like “Listening instead of reading gives you freedom to do X/enables you to do X”. I also don’t know what the sentence “Having to read everything can be limiting – especially in terms of audience” exactly means. I think using positive words like “Some people prefer listening instead of reading text. Making reading content[sorry, jargony] possible broadens your audience.” (Not the best wording, but I hope you get the gist.)

**Comment by nitedog** [comment]
Removed.
