### ISSUE TITLE
[Script 6: Notifications and Feedback] Error not bad enough

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#18]
In sequence 4 the confusing error is given as 'incorrect date format'.

I don't think this is entirely confusing enough! Perhaps something like:

> field12 wrong

or

> Incorrect first name

Seriously, I have seen the latter!

**Comment by bakkenb** [comment]
LOL about the name. That is funny. I am sure it was about some character used instead of the actual name, but that is funny!

I agree about this comment. Most of us get that date format error from time to time and we have figured out to just try formats until it works. A more obscure error like Kevin is suggesting may be better. It needs to be confusing. The video can show that it is for a date field, but the error message can be more obscure so that one is not sure if it is the date format or something else all together.

**Comment by nitedog** [comment]
From James:

> Again I warn to make the techy/cryptic message realistic and not over the top or cartoonish if we want to keep people engaged and empathetic versus just entertained.

**Comment by nitedog** [comment]
Now use "invalid input", which is ambiguous - is it the date format, range, or other issue?
