### ISSUE TITLE
[Notifications] title

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-showcase-examples#186]
From @dboudreau 

> I don't like that title, I find the the use of the word "notifications" makes it unnecessarily complex and confusing. I would much rather prefer we use the word "instructions" instead. The video itself is great, but I would advocate for changing the title.

**Comment by bakkenb** [comment]
I believe this video is about something that occurs or pops onto a page. A notification will pop up, feedback will occur with a pop-up or loading a new page. Instructions however are generally already on the page instructing people or giving directions. Usually there is no issue with those because they are already on the page. I believe the title is okay as is.

**Comment by nitedog** [comment]
This was discussed during EOWG, and we concluded that the video is more focused on "notifications" rather than "instructions". Such a title change at this stage would conflict with the contents of the video.
