### ISSUE TITLE
overall still

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-showcase-examples#235]
I'd like an overall still for all the videos- of various sizes, including small. I'm currently thinking of including that in the [WAI Highlight](https://www.w3.org/WAI/#highlights)

**Comment by bakkenb** [comment]
Just a thought. If one of the thumbnail stills is used for this I would recommend the Keyboard Compatibility one. If it is not one of the thumbnail stills, then there is a lot of footage to choose from. ;)

**Comment by nitedog** [comment]
Please propose a scene from the footage that represents the resource well. @slhenry @bakkenb @haltersweb

**Comment by bakkenb** [comment]
What about at 14 Seconds in the Text to Speech video. 
Rationale: Person, laptop, service animal, nice setting - should catch the eye and make people be interested in what the videos are about.

**Comment by nitedog** [comment]
Good idea @bakkenb! Either puppies or kittens ;) Seriously, I agree that it is a good scene. Just that it is a blind person, and many people already think that web accessibility is only about blind people. Is that an issue - would this as the main image reinforce that unfortunate myth?

**Comment by bakkenb** [comment]
I understand your point @nitedog. Trying to focus on a scene with a high incidence disability is hard to do because typically you don't see them visually. Since this was a still image, I was trying to find something where you could see or infer the disability being present, but not overwhelming like the sip/puff assistive technology scene. 

I get your point and leave it up to others to weigh in on.

**Comment by shawna-slh** [comment]
Good points, all above.

More perspectives: Animals attract attention in marketing. The still for the announcements is a outreach/promotion/marketing piece. Judy thinks the positive marketing value of the dog outweighs the accessibility-is-about-more-than-blind issue. I think I agree. Also, since once people get to the page we have a good coverage of non-blind issues, I'm OK with the still for this purpose including guide dog.

If using dog:
- The scene around 0:14 has the dog passive - which isn't great.
- The scene around 0:36 has more active dog _and_ mobile (although mobile isn't totally clear in stall) - so maybe this one would be better?

**Comment by bakkenb** [comment]
To me, it is easier to know that it is a service dog when they are inside. The dog is passive because the man is sitting down and working on his laptop, but you can see the harness and know it is a service dog.

The shot outside is a bit odd for a still. He seems to be sitting in a lawn chair all on is own with his phone and his dog is at attention like he is waiting for a command or a ball to be thrown. 

Just my opinion, but I feel the inside shot just seems more professional looking and peaceful, like everything is working properly for this person.

**Comment by shawna-slh** [comment]
I was mostly thinking: What image captures my attention and makes me want to click on it. :)

**Comment by shawna-slh** [comment]
If we want to go with existing still, thoughts on my top suggestions:
- video captions (people at table) - pro: people and computer. was my first choice, but then I wondered if W3Cers would just think it's a f2f? :-)
- clear layout & design (pizza) - in the small image the closed eyes & body position not too distracting. pro: person and computer, looks active.
- keyboard compatibility (person in wheelchair) - in the small image, the disability isn't too overwhelming. pro: person and computer.
- voice recognition (woman with mug) - pro: active person with computer.
- understandable content (pointing to computer) - con: no faces. possible con: pointing is rude in some cultures, although pointing to computer may be OK.
- customizable text (guy with toast) - the most active, but also no computer -- but maybe that's fine for a marketing image - it makes me curious to click on it and see WHY W3C has a picture of toast :-)

I'm not set on any and happy to use what @nitedog, @bakkenb, @haltersweb others want.

**Comment by nitedog** [comment]
Here are some more ideas for scenes:
- AD-version of "Speech": at ~0:19-0:21 (on the sofa with guidedog); at ~0:21 (just the guidedog); or at ~0:54-0:57 (sitting outside).
- AD-version of "Voice": at ~1:13-1:15 (standing outside).

**Comment by nitedog** [comment]
Selected: http://w3c.github.io/wai-showcase-examples/img/overview.jpg
