### ISSUE TITLE
[Script 8: Text Customization] Text example may not be as vital as all that

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-showcase-examples#24]
Not sure about the example. It is extremely rare that a toilet sign would not include iconography to support the text.

This may need an example where iconography is not that common. Trouble is, changing this changes the whole narrative, which otherwise works well.

Perhaps rather than ladies/gents, maybe just "Toilets". This is a bit more commonly seen without iconography.

**Comment by shawna-slh** [comment]
fyi, The US does not use the term "toilets" publicly - it would be crass. (see related comment: https://github.com/w3c/wai-showcase-examples/issues/27#issuecomment-182108265)

**Comment by bakkenb** [comment]
Background...
The original visual from the production company used the word "Toilets". Adina and I asked that it be replaced because toilets would never be used in the US. I asked about "Restroom(s)" and that was not easily recognized in Europe. We settled on ladies/gents but are open to more suggestions.

**Comment by nitedog** [comment]
Script has been revised and this example has been removed.
