### ISSUE TITLE
Move or delete

### ISSUE THREAD

**Issue by susanatx** [w3c/wai-showcase-examples#257]
This paragraph "Web accessibility is essential for people with disabilities and useful for all. Learn about the impact of accessibility and the benefits for everyone in a variety of situations." is unnecessary to repeat at the top of every single video's page. I recommend moving it beneath the "Perspectives Videos" as it relates to the video collection as a whole, not an individual video. (At least not in the current, generic sentence.)

**Comment by bakkenb** [comment]
I completely understand what @susanatx is raising as an issue. When you pointed it out, at first I was in agreement that the sentence could go right after the "Perspective Videos" heading towards the bottom of the page as you suggest. Then I started thinking about the fact that some users will come to this resource with a link to a specific video page. If that is the case, would it be helpful to have the sentence at the top rather than down below? Not sure which I prefer now.

**Comment by nitedog** [comment]
EOWG took a resolution to keep this intro sentence, given its importance and brevity.
