### ISSUE TITLE
[perspectives - captions] affordable to whom?

### ISSUE THREAD

**Issue by chaals** [w3c/wai-showcase-examples#294]
The sentence "For many languages there are captioning services that are affordable." seems problematic. It is possible to buy a device, make a lot of video, and put it online for less than common prices to caption an hour of video.

Which is not to say that transcription services are expensive, just that as phrased there are a lot of apparent assumptions about how much money people may have.

**Comment by nitedog** [comment]
The issue is that some people reflexively think that captioning is "too expensive" without looking into the prices. Often it is far cheaper than they thought. Of course, not in all languages. Any thoughts on how to better communicate this aspect? How about this:
- For many languages, the prices for captioning services have been decreasing.
